receivers:

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

      http:
        endpoint: 0.0.0.0:4318


  file_log/docker:

    include:
      - /var/lib/docker/containers/*/*.log

    start_at: beginning

    include_file_path: true

    operators:

      - type: container


processors:

  batch:
    timeout: 10s
    send_batch_size: 1024



exporters:


  debug:
    verbosity: normal


  otlp_http/dynatrace:

    endpoint: https://cqs16759.live.dynatrace.com/api/v2/otlp

    headers:

      Authorization: "Api-Token ${DT_API_TOKEN}"



  otlp_grpc/jaeger:

    endpoint: jaeger:4317

    tls:

      insecure: true



service:


  pipelines:


    traces:

      receivers:

        - otlp

      processors:

        - batch

      exporters:

        - debug
        - otlp_grpc/jaeger
        - otlp_http/dynatrace



    metrics:

      receivers:

        - otlp

      processors:

        - batch

      exporters:

        - debug
        - otlp_http/dynatrace



    logs:

      receivers:

        - file_log/docker
        - otlp

      processors:

        - batch

      exporters:

        - debug
        - otlp_http/dynatrace
